### ISSUE TITLE
Gør klar til at lege bank dværg

### ISSUE THREAD

**Issue by holsta** [HobroRollespil/hobrorollespil.dk#15]
- [x] Skriveredskab
- [x] Noteringspapir
- [x] Beholder/kiste
- [x] "Bank" skilt

**Comment by LittleBookLover** [comment]
@SoerenHammer  Hej Søren. Var den ene guldkiste til bank dværgen?

**Comment by holsta** [comment]
Jeg bruger en fed blyant i stedet for fjerpen.
