### ISSUE TITLE
Mail til foreningen

### ISSUE THREAD

**Issue by LittleBookLover** [HobroRollespil/hobrorollespil.dk#18]
- [x] Opret email

- [x] Kald den bestyrelse@hobrorollespil.dk

- [x] Videregiv oplysninger til brug af email

- [ ] Få et skulderklap få et godt stykke arbejde

- [ ] Giv flødeboller for at have været for langsom til at udføre opgaven (Øl er også acceptabelt)

**Comment by LittleBookLover** [comment]
Hvordan går det med at få oprettet emailen? :)

**Comment by holsta** [comment]
Jeg har oprettet en konto hos One.com i foreningens navn og betalt for et år. Jeg afventer pt domæne redelegering. Det burde være sket fredag, men er ikke gået igennem endnu.

**Comment by SoerenHammer** [comment]
Hvis du har en kvittering så kan du jo få beløbet refunderet - Jeg tror foreningen har penge nok til at kan lade sig gøre :P

**Comment by holsta** [comment]
@SoerenHammer  Besøg https://login.one.com/mail

Brugernavn: bestyrelsen@hobrorollespil.dk
Kodeord: Følger et hemmeligt sted

**Comment by holsta** [comment]
Det er bekræftet, at Søren kan logge ind i webmail.

**Comment by LittleBookLover** [comment]
Super godt klaret! Jeg sender et virtuelt klap på skulderen (Y)
