### ISSUE TITLE
Få styr på skilte

### ISSUE THREAD

**Issue by holsta** [HobroRollespil/hobrorollespil.dk#2]
Vurder hvilke skilte der skal sættes op og hvordan de laves.
- [x] Indkørsel frabedes
- [x] Parkering langs vejkanten
- [x] Parkering ved Hørby Kirke
- [x] Betaling
- [x] Karakter-biksen /cancelled
- [x] våbentjek/rustningstjek
- [x] vejviser-skilte
- [ ] reklame-skilte
- [ ] Spillet er aflyst
- [ ] Skilt til smeden

**Comment by SoerenHammer** [comment]
Issuet lukkes. Skilte laves efter behov, og får individuel issue som nødvendigt.
