### ISSUE TITLE
General forsamling 2017

### ISSUE THREAD

**Issue by LittleBookLover** [HobroRollespil/hobrorollespil.dk#20]
- [x] Dagsorden

- [x] Forslag til rettelser i vedtægter

- [x] Lokale

- [x] Forfriskninger til mødet 

- [x] Dirigent pind

- [x] Regnskab

**Comment by holsta** [comment]
Jeg giver Søren fuldmagt til at stemme på mine vegne, da jeg ikke selv kan være med.

**Comment by SoerenHammer** [comment]
Generalforsamling er blevet afholdt. Nyt issue bliver oprettet til opdateringer af resultaterne.
